SET(CMAKE_C_COMPILER /usr/bin/gcc)
SET(CMAKE_CXX_COMPILER /usr/bin/g++)
SET(CMAKE_INSTALL_PREFIX $ENV{HOME} CACHE PATH "default install path" FORCE)
SET(CMAKE_BUILD_TYPE Debug CACHE STRING "Debug build" FORCE)
